# Generated by Django 3.1.5 on 2021-01-31 22:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Addition',
                'verbose_name_plural': 'Additions',
                'db_table': 'sw_addition',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de compra')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total de la compra')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'db_table': 'sw_bill',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('id_doc', models.IntegerField(help_text='Por favor, solo ingrese el valor numérico de su número de identificación.', unique=True, verbose_name='número de identificación')),
                ('first_name', models.CharField(max_length=30, verbose_name='primer nombre')),
                ('middle_name', models.CharField(max_length=30, null=True, verbose_name='segundo nombre')),
                ('surname', models.CharField(max_length=30, verbose_name='primer apellido')),
                ('second_surname', models.CharField(max_length=30, null=True, verbose_name='segundo apellido')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'sw_client',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, verbose_name='nombre del producto en venta')),
                ('photo', models.ImageField(null=True, upload_to='uploads/', verbose_name='foto del producto')),
                ('type_product', models.IntegerField(default=4, verbose_name='producto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='precio')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'db_table': 'sw_combo',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, verbose_name='nombre del producto en venta')),
                ('photo', models.ImageField(null=True, upload_to='uploads/', verbose_name='foto del producto')),
                ('type_product', models.IntegerField(default=2, verbose_name='producto')),
                ('type_drink', models.IntegerField(choices=[(1, 'Refresco'), (2, 'Jugo'), (3, 'Café'), (4, 'Agua')], verbose_name='tipo de bebida')),
            ],
            options={
                'verbose_name': 'Drink',
                'verbose_name_plural': 'Drinks',
                'db_table': 'sw_drink',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, verbose_name='nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='precio')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'sw_ingredients',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('number', models.IntegerField(default=1, verbose_name='número del pedido')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='sub total')),
                ('combo', models.ForeignKey(limit_choices_to={'is_activated': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.combo')),
                ('drink', models.ForeignKey(limit_choices_to={'is_activated': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.drink')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'sw_order',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleProm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('start_hour', models.TimeField(verbose_name='hora en el que inicia la oferta')),
                ('end_hour', models.TimeField(verbose_name='hora en el que termina la oferta')),
                ('monday', models.BooleanField(default=False, verbose_name='lunes')),
                ('tuesday', models.BooleanField(default=False, verbose_name='martes')),
                ('wednesday', models.BooleanField(default=False, verbose_name='miércoles')),
                ('thursday', models.BooleanField(default=False, verbose_name='jueves')),
                ('friday', models.BooleanField(default=False, verbose_name='viernes')),
                ('saturday', models.BooleanField(default=False, verbose_name='sábado')),
                ('sunday', models.BooleanField(default=False, verbose_name='domingo')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'sw_schedule_prom',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SideDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, verbose_name='nombre del producto en venta')),
                ('photo', models.ImageField(null=True, upload_to='uploads/', verbose_name='foto del producto')),
                ('type_product', models.IntegerField(default=3, verbose_name='producto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='precio')),
            ],
            options={
                'verbose_name': 'Side Dish',
                'verbose_name_plural': 'Side Dishes',
                'db_table': 'sw_side_dish',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, verbose_name='tamaño del producto')),
                ('product', models.IntegerField(choices=[(1, 'Sandwich'), (2, 'Drink')], verbose_name='producto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='precio')),
                ('photo', models.ImageField(null=True, upload_to='uploads/', verbose_name='foto del producto')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'db_table': 'sw_size',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('photo', models.ImageField(null=True, upload_to='uploads/', verbose_name='foto del producto')),
                ('type_product', models.IntegerField(default=1, verbose_name='producto')),
                ('ingredients', models.ManyToManyField(through='sandwichesweb.Addition', to='sandwichesweb.Ingredient')),
                ('size', models.ForeignKey(limit_choices_to={'is_activated': True, 'product': 1}, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.size')),
            ],
            options={
                'verbose_name': 'Sandwich',
                'verbose_name_plural': 'Sandwiches',
                'db_table': 'sw_sandwich',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuantityOfProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('product', models.CharField(max_length=30, verbose_name='tipo de producto')),
                ('quantity', models.IntegerField(default=0, verbose_name='cantidad de este tipo de producto')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.bill')),
            ],
            options={
                'verbose_name': 'Quantity of products',
                'verbose_name_plural': 'Quantity of products',
                'db_table': 'sw_quantity_of_products',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de compra')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total de la compra')),
                ('client', models.ForeignKey(limit_choices_to={'is_activated': True}, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.client')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'db_table': 'sw_purchase',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=48, verbose_name='nombre de la oferta')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='descripción de la oferta')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='fecha en que inicia la oferta')),
                ('end_date', models.DateField(null=True, verbose_name='fecha en que termina la oferta')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='descuento de la oferta')),
                ('schedule', models.ForeignKey(limit_choices_to={'is_activated': True}, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.scheduleprom')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'sw_promotion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('order', models.ForeignKey(limit_choices_to={'is_activated': True}, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.order')),
                ('promotion', models.ForeignKey(limit_choices_to={'is_activated': True}, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.promotion')),
            ],
            options={
                'verbose_name': 'promotion application',
                'verbose_name_plural': 'promotion applications',
                'db_table': 'sw_prom_application',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsInCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('combo', models.ForeignKey(limit_choices_to={'is_activated': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.combo')),
                ('drink', models.ForeignKey(limit_choices_to={'is_activated': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.drink')),
                ('sandwich', models.ForeignKey(limit_choices_to={'is_activated': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.sandwich')),
                ('side_dish', models.ForeignKey(limit_choices_to={'is_activated': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.sidedish')),
            ],
            options={
                'verbose_name': 'Products in combo',
                'verbose_name_plural': 'Products in combo',
                'db_table': 'sw_products_in_combo',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(limit_choices_to={'is_activated': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.purchase'),
        ),
        migrations.AddField(
            model_name='order',
            name='sandwich',
            field=models.ForeignKey(limit_choices_to={'is_activated': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.sandwich'),
        ),
        migrations.AddField(
            model_name='order',
            name='side_dish',
            field=models.ForeignKey(limit_choices_to={'is_activated': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.sidedish'),
        ),
        migrations.AddField(
            model_name='drink',
            name='size',
            field=models.ForeignKey(limit_choices_to={'is_activated': True, 'product': 2}, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.size'),
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('product', models.CharField(max_length=30, verbose_name='tipo de producto')),
                ('size', models.CharField(max_length=30, null=True, verbose_name='tamaño del producto')),
                ('ingredients', models.CharField(max_length=100, null=True, verbose_name='ingredientes del sándwich')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='precio del producto')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.bill')),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
                'db_table': 'sw_detail',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='combo',
            name='drinks',
            field=models.ManyToManyField(through='sandwichesweb.ProductsInCombo', to='sandwichesweb.Drink'),
        ),
        migrations.AddField(
            model_name='combo',
            name='sandwiches',
            field=models.ManyToManyField(through='sandwichesweb.ProductsInCombo', to='sandwichesweb.Sandwich'),
        ),
        migrations.AddField(
            model_name='combo',
            name='side_dishes',
            field=models.ManyToManyField(through='sandwichesweb.ProductsInCombo', to='sandwichesweb.SideDish'),
        ),
        migrations.AddField(
            model_name='bill',
            name='purchase',
            field=models.OneToOneField(limit_choices_to={'is_activated': True}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase', related_query_name='purchase', to='sandwichesweb.purchase'),
        ),
        migrations.AddField(
            model_name='addition',
            name='ingredient',
            field=models.ForeignKey(limit_choices_to={'is_activated': True}, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.ingredient'),
        ),
        migrations.AddField(
            model_name='addition',
            name='sandwich',
            field=models.ForeignKey(limit_choices_to={'is_activated': True}, on_delete=django.db.models.deletion.CASCADE, to='sandwichesweb.sandwich'),
        ),
    ]
