# Generated by Django 3.1.5 on 2021-02-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwichesweb', '0003_remove_purchase_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='nombre del producto'),
        ),
    ]
