# Generated by Django 3.1.5 on 2021-02-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandwichesweb', '0004_auto_20210201_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantityofproducts',
            options={'verbose_name': 'Cantidad de productos comprados', 'verbose_name_plural': 'Cantidad de productos comprados'},
        ),
    ]
