# Generated by Django 3.1.5 on 2021-02-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwichesweb', '0006_auto_20210201_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='product',
            field=models.CharField(choices=[('Sándwich', 'Sándwich'), ('Bebida', 'Bebida'), ('Acompañante', 'Acompañante'), ('Combo', 'Combo')], default='Sándwich', max_length=30, verbose_name='tipo de producto'),
        ),
    ]
